# agent.py
"""
Main ResearchAgent implementation that orchestrates the research process.
Generated by Claude.
"""
from typing import List, Dict, Any, Optional
import openai
from openai.agent import Agent, Tool
from .tools.web_search_tool import WebSearchTool
from .tools.document_analysis_tool import DocumentAnalysisTool
from .tools.information_extraction_tool import InformationExtractionTool
from .tools.citation_generation_tool import CitationGenerationTool
from .tools.report_generation_tool import ReportGenerationTool
from .tools.data_analysis_tool import DataAnalysisTool
from .utils.helpers import format_research_problem, track_research_progress

class ResearchAgent:
    """
    The primary agent responsible for orchestrating the entire research process.
    It takes the user's research problem definition as input and generates a comprehensive
    research report with proper citations.
    """
    
    def __init__(self, api_key: str, model: str = "gpt-4-turbo"):
        """
        Initialize the ResearchAgent.
        
        Args:
            api_key: OpenAI API key
            model: The model to use for the agent (default: gpt-4-turbo)
        """
        self.api_key = api_key
        self.model = model
        openai.api_key = api_key
        
        # Initialize tools
        self.web_search_tool = WebSearchTool()
        self.document_analysis_tool = DocumentAnalysisTool()
        self.information_extraction_tool = InformationExtractionTool()
        self.citation_generation_tool = CitationGenerationTool()
        self.report_generation_tool = ReportGenerationTool()
        self.data_analysis_tool = DataAnalysisTool()
        
        # Create the OpenAI agent
        self.tools = [
            Tool(
                name="web_search",
                description="Search the web for information related to the research topic",
                function=self.web_search_tool.search
            ),
            Tool(
                name="document_analysis",
                description="Analyze and extract text from documents",
                function=self.document_analysis_tool.analyze
            ),
            Tool(
                name="information_extraction",
                description="Extract specific information from text",
                function=self.information_extraction_tool.extract
            ),
            Tool(
                name="citation_generation",
                description="Generate citations for claims based on sources",
                function=self.citation_generation_tool.generate_citation
            ),
            Tool(
                name="report_generation",
                description="Generate a structured research report",
                function=self.report_generation_tool.generate_report
            ),
            Tool(
                name="data_analysis",
                description="Analyze numerical or structured data",
                function=self.data_analysis_tool.analyze
            )
        ]
        
        # Initialize agent state
        self.research_state = {
            "problem": None,
            "sub_questions": [],
            "findings": [],
            "citations": [],
            "report": None
        }
        
    def create_agent(self) -> Agent:
        """Create and return an OpenAI Agent instance with research capabilities."""
        instructions = """
        You are an advanced research agent capable of conducting thorough research on any topic.
        Your goal is to create well-researched, accurate reports with proper citations.
        
        Follow these steps for any research task:
        1. Analyze the research problem and break it down into sub-questions
        2. For each sub-question, search for relevant information using web_search
        3. Analyze documents and extract key information using document_analysis and information_extraction
        4. For each claim or piece of information, generate a proper citation using citation_generation
        5. Synthesize findings into a comprehensive report using report_generation
        6. If you encounter data that needs analysis, use data_analysis
        
        Always maintain academic integrity by:
        - Citing all sources properly
        - Distinguishing between facts and opinions
        - Presenting balanced perspectives on controversial topics
        - Verifying information across multiple sources when possible
        """
        
        return Agent(
            model=self.model,
            tools=self.tools,
            instructions=instructions
        )
    
    def conduct_research(self, research_problem: str, citation_style: str = "APA") -> Dict[str, Any]:
        """
        Conduct research on the given problem and generate a report with citations.
        
        Args:
            research_problem: The research problem to investigate
            citation_style: The citation style to use (APA, MLA, Chicago, etc.)
            
        Returns:
            A dictionary containing the research report and metadata
        """
        # Format the research problem
        formatted_problem = format_research_problem(research_problem)
        self.research_state["problem"] = formatted_problem
        
        # Configure citation style
        self.citation_generation_tool.set_citation_style(citation_style)
        
        # Create the agent
        agent = self.create_agent()
        
        # Starting the research process
        initial_message = f"""
        I need to conduct thorough research on the following topic:
        
        {formatted_problem}
        
        Please help me create a comprehensive research report with proper {citation_style} citations.
        Begin by breaking down this problem into manageable sub-questions for investigation.
        """
        
        # Run the agent
        result = agent.run(initial_message)
        
        # Process the agent's output and update the research state
        self._process_agent_output(result)
        
        return {
            "problem": self.research_state["problem"],
            "report": self.research_state["report"],
            "citations": self.research_state["citations"],
            "sub_questions": self.research_state["sub_questions"],
            "findings": self.research_state["findings"]
        }
    
    def _process_agent_output(self, result: Dict[str, Any]) -> None:
        """Process the output from the agent and update the research state."""
        # Extract the final report
        if "report" in result:
            self.research_state["report"] = result["report"]
        else:
            # If the agent didn't explicitly return a report, use the last message
            self.research_state["report"] = result["messages"][-1]["content"]
        
        # Extract citations if available
        if "citations" in result:
            self.research_state["citations"] = result["citations"]
        
        # Extract sub-questions if available
        if "sub_questions" in result:
            self.research_state["sub_questions"] = result["sub_questions"]
        
        # Extract findings if available
        if "findings" in result:
            self.research_state["findings"] = result["findings"]
            
    def save_report(self, file_path: str) -> None:
        """Save the research report to a file."""
        if not self.research_state["report"]:
            raise ValueError("No research report available to save")
        
        with open(file_path, "w") as f:
            f.write(self.research_state["report"])
            
    def save_research_data(self, file_path: str) -> None:
        """Save all research data including citations to a JSON file."""
        import json
        
        if not self.research_state["report"]:
            raise ValueError("No research data available to save")
        
        with open(file_path, "w") as f:
            json.dump(self.research_state, f, indent=2)
