
# tools/citation_generation_tool.py
# Generated by Claude

"""
Tool for generating citations for claims based on sources.
"""
from typing import Dict, List, Any, Optional
import re
import datetime

class CitationGenerationTool:
    """Tool for generating citations for claims made in the research process."""
    
    def __init__(self):
        """Initialize the CitationGenerationTool."""
        self.citation_style = "APA"
        self.citation_db = []  # Database of generated citations
        self.claim_citation_map = {}  # Map claims to citations
    
    def set_citation_style(self, style: str) -> None:
        """Set the citation style to use."""
        self.citation_style = style
    
    def generate_citation(self, source: Dict[str, Any], claim: Optional[str] = None) -> Dict[str, Any]:
        """
        Generate a citation for a source and optionally associate it with a claim.
        
        Args:
            source: Dictionary containing source information
            claim: Optional claim to associate with this citation
            
        Returns:
            A dictionary containing the generated citation
        """
        # Generate the citation based on the source type and style
        if source.get("type") == "web" or source.get("source_type") == "web":
            citation = self._generate_web_citation(source)
        elif source.get("type") == "book" or source.get("source_type") == "book":
            citation = self._generate_book_citation(source)
        elif source.get("type") == "journal" or source.get("source_type") == "journal":
            citation = self._generate_journal_citation(source)
        else:
            # Default to web citation
            citation = self._generate_web_citation(source)
        
        # Add to citation database
        citation_id = len(self.citation_db)
        citation["id"] = citation_id
        self.citation_db.append(citation)
        
        # Map claim to citation if provided
        if claim:
            if claim not in self.claim_citation_map:
                self.claim_citation_map[claim] = []
            self.claim_citation_map[claim].append(citation_id)
        
        return citation
    
    def _generate_web_citation(self, source: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a citation for a web source."""
        # Extract required information
        title = source.get("title", "Untitled")
        url = source.get("url", source.get("link", ""))
        author = source.get("author", "")
        site_name = source.get("site_name", source.get("source_name", ""))
        published_date = source.get("published_date", "")
        retrieved_date = source.get("retrieved_date", datetime.datetime.now().strftime("%Y-%m-%d"))
        
        # Format citation based on style
        if self.citation_style == "APA":
            if author:
                in_text = f"({author}, {published_date.split('-')[0] if published_date else 'n.d.'})"
                reference = f"{author}. ({published_date.split('-')[0] if published_date else 'n.d.'}). {title}. {site_name}. Retrieved {retrieved_date}, from {url}"
            else:
                in_text = f"({title}, {published_date.split('-')[0] if published_date else 'n.d.'})"
                reference = f"{title}. ({published_date.split('-')[0] if published_date else 'n.d.'}). {site_name}. Retrieved {retrieved_date}, from {url}"
        
        elif self.citation_style == "MLA":
            if author:
                in_text = f"({author})"
                reference = f"{author}. \"{title}.\" {site_name}, {published_date if published_date else 'n.d.'}, {url}. Accessed {retrieved_date}."
            else:
                in_text = f"(\"{title}\")"
                reference = f"\"{title}.\" {site_name}, {published_date if published_date else 'n.d.'}, {url}. Accessed {retrieved_date}."
        
        elif self.citation_style == "Chicago":
            if author:
                in_text = f"({author}, {published_date.split('-')[0] if published_date else 'n.d.'})"
                reference = f"{author}. \"{title}.\" {site_name}. {published_date if published_date else 'n.d.'}. {url}."
            else:
                in_text = f"({site_name}, {published_date.split('-')[0] if published_date else 'n.d.'})"
                reference = f"{site_name}. \"{title}.\" {published_date if published_date else 'n.d.'}. {url}."
        
        else:
            # Default format
            in_text = f"({url})"
            reference = f"{title}. {url}"
        
        return {
            "source_type": "web",
            "in_text_citation": in_text,
            "reference": reference,
            "style": self.citation_style,
            "source_data": {
                "title": title,
                "url": url,
                "author": author,
                "site_name": site_name,
                "published_date": published_date,
                "retrieved_date": retrieved_date
            }
        }
    
    def _generate_book_citation(self, source: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a citation for a book."""
        # Extract required information
        title = source.get("title", "Untitled")
        author = source.get("author", "")
        year = source.get("year", source.get("published_date", "")).split("-")[0] if source.get("year", source.get("published_date", "")) else "n.d."
        publisher = source.get("publisher", "")
        location = source.get("location", "")
        
        # Format citation based on style
        if self.citation_style == "APA":
            in_text = f"({author}, {year})"
            reference = f"{author}. ({year}). {title}. {publisher}."
        
        elif self.citation_style == "MLA":
            in_text = f"({author} {year})"
            reference = f"{author}. {title}. {publisher}, {year}."
        
        elif self.citation_style == "Chicago":
            in_text = f"({author}, {year})"
            reference = f"{author}. {title}. {location}: {publisher}, {year}."
        
        else:
            # Default format
            in_text = f"({author}, {year})"
            reference = f"{author}. {title}. {publisher}, {year}."
        
        return {
            "source_type": "book",
            "in_text_citation": in_text,
            "reference": reference,
            "style": self.citation_style,
            "source_data": {
                "title": title,
                "author": author,
                "year": year,
                "publisher": publisher,
                "location": location
            }
        }
    
    def _generate_journal_citation(self, source: Dict[str, Any]) -> Dict[str, Any]:
        """Generate a citation for a journal article."""
        # Extract required information
        title = source.get("title", "Untitled")
        author = source.get("author", "")
        year = source.get("year", source.get("published_date", "")).split("-")[0] if source.get("year", source.get("published_date", "")) else "n.d."
        journal = source.get("journal", "")
        volume = source.get("volume", "")
        issue = source.get("issue", "")
        pages = source.get("pages", "")
        doi = source.get("doi", "")
        
        # Format citation based on style
        if self.citation_style == "APA":
            in_text = f"({author}, {year})"
            reference = f"{author}. ({year}). {title}. {journal}, {volume}({issue}), {pages}. {f'https://doi.org/{doi}' if doi else ''}"
        
        elif self.citation_style == "MLA":
            in_text = f"({author})"
            reference = f"{author}. \"{title}.\" {journal}, vol. {volume}, no. {issue}, {year}, pp. {pages}. {f'DOI: {doi}' if doi else ''}"
        
        elif self.citation_style == "Chicago":
            in_text = f"({author}, {year})"
            reference = f"{author}. \"{title}.\" {journal} {volume}, no. {issue} ({year}): {pages}. {f'https://doi.org/{doi}' if doi else ''}"
        
        else:
            # Default format
            in_text = f"({author}, {year})"
            reference = f"{author}. {title}. {journal}, {volume}({issue}), {pages}."
        
        return {
            "source_type": "journal",
            "in_text_citation": in_text,
            "reference": reference,
            "style": self.citation_style,
            "source_data": {
                "title": title,
                "author": author,
                "year": year,
                "journal": journal,
                "volume": volume,
                "issue": issue,
                "pages": pages,
                "doi": doi
            }
        }
    
    def verify_claim(self, claim: str, source_content: str) -> Dict[str, Any]:
        """
        Verify if a claim is supported by the source content.
        
        Args:
            claim: The claim to verify
            source_content: The content of the source to check against
            
        Returns:
            A dictionary containing verification results
        """
        # In a real implementation, this would use more sophisticated NLP techniques
        # For demonstration, we'll use a simple similarity-based approach
        
        # Convert to lowercase for case-insensitive comparison
        claim_lower = claim.lower()
        content_lower = source_content.lower()
        
        # Check if the claim words appear in the content
        claim_words = set(re.findall(r'\w+', claim_lower))
        significant_words = [word for word in claim_words if len(word) > 3]  # Only consider words with > 3 chars
        
        found_words = 0
        for word in significant_words:
            if word in content_lower:
                found_words += 1
        
        # Calculate a simple similarity score
        if len(significant_words) > 0:
            similarity = found_words / len(significant_words)
        else:
            similarity = 0
        
        verification_result = {
            "claim": claim,
            "supported": similarity > 0.7,  # Arbitrary threshold
            "confidence": similarity,
            "match_details": {
                "significant_words": len(significant_words),
                "found_words": found_words
            }
        }
        
        return verification_result
    
    def generate_bibliography(self) -> Dict[str, Any]:
        """
        Generate a bibliography from all citations in the database.
        
        Returns:
            A dictionary containing the bibliography
        """
        references = []
        for citation in self.citation_db:
            references.append(citation["reference"])
        
        # Sort references alphabetically (typical for most citation styles)
        references.sort()
        
        return {
            "references": references,
            "style": self.citation_style,
            "count": len(references)
        }
    
    def get_citation_for_claim(self, claim: str) -> List[Dict[str, Any]]:
        """
        Get citations associated with a specific claim.
        
        Args:
            claim: The claim to find citations for
            
        Returns:
            A list of citation dictionaries
        """
        if claim in self.claim_citation_map:
            citation_ids = self.claim_citation_map[claim]
            return [self.citation_db[cid] for cid in citation_ids]
        else:
            return []
