# tools/data_analysis_tool.py
# Generated by Claude

"""
Tool for analyzing numerical or structured data.
"""
from typing import Dict, List, Any, Optional
import json
import re

class DataAnalysisTool:
    """Tool for analyzing structured or numerical data encountered during research."""
    
    def __init__(self):
        """Initialize the DataAnalysisTool."""
        pass
    
    def analyze(self, 
                data: Any, 
                analysis_type: str, 
                parameters: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Analyze data according to the specified analysis type.
        
        Args:
            data: The data to analyze (can be in various formats)
            analysis_type: The type of analysis to perform
            parameters: Optional parameters for the analysis
            
        Returns:
            A dictionary containing the analysis results
        """
        if parameters is None:
            parameters = {}
        
        # Parse the data if it's a string
        if isinstance(data, str):
            try:
                # Try to parse as JSON
                parsed_data = json.loads(data)
            except json.JSONDecodeError:
                # If not JSON, try to parse as CSV
                parsed_data = self._parse_csv(data)
        else:
            parsed_data = data
        
        # Choose analysis method based on analysis_type
        if analysis_type.lower() == "descriptive_statistics":
            result = self._descriptive_statistics(parsed_data, parameters)
        elif analysis_type.lower() == "correlation":
            result = self._correlation_analysis(parsed_data, parameters)
        elif analysis_type.lower() == "trend_analysis":
            result = self._trend_analysis(parsed_data, parameters)
        elif analysis_type.lower() == "comparison":
            result = self._comparison_analysis(parsed_data, parameters)
        elif analysis_type.lower() == "frequency":
            result = self._frequency_analysis(parsed_data, parameters)
        else:
            # Default to basic analysis
            result = self._basic_analysis(parsed_data, parameters)
        
        return {
            "analysis_type": analysis_type,
            "parameters": parameters,
            "results": result
        }
    
    def _parse_csv(self, data: str) -> List[Dict[str, Any]]:
        """Parse CSV string into a list of dictionaries."""
        lines = data.strip().split('\n')
        if not lines:
            return []
        
        # Parse header
        headers = [h.strip() for h in lines[0].split(',')]
        
        result = []
        for i in range(1, len(lines)):
            values = lines[i].split(',')
            row_dict = {}
            for j in range(min(len(headers), len(values))):
                # Try to convert to number if possible
                value = values[j].strip()
                try:
                    if '.' in value:
                        row_dict[headers[j]] = float(value)
                    else:
                        row_dict[headers[j]] = int(value)
                except ValueError:
                    row_dict[headers[j]] = value
            
            result.append(row_dict)
        
        return result
    
    def _descriptive_statistics(self, data: Any, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Calculate descriptive statistics for the data."""
        result = {}
        
        # If data is a list of dictionaries (tabular data)
        if isinstance(data, list) and all(isinstance(item, dict) for item in data):
            # For each numeric column, calculate statistics
            for column in data[0].keys():
                values = [item[column] for item in data if column in item and isinstance(item[column], (int, float))]
                
                if values:
                    column_stats = {
                        "count": len(values),
                        "mean": sum(values) / len(values) if values else None,
                        "min": min(values) if values else None,
                        "max": max(values) if values else None,
                        "median": sorted(values)[len(values) // 2] if values else None
                    }
                    
                    # Calculate standard deviation
                    mean = column_stats["mean"]
                    variance = sum((x - mean) ** 2 for x in values) / len(values) if values else 0
                    column_stats["std_dev"] = variance ** 0.5
                    
                    result[column] = column_stats
        
        # If data is a list of numbers
        elif isinstance(data, list) and all(isinstance(item, (int, float)) for item in data):
            result = {
                "count": len(data),
                "mean": sum(data) / len(data) if data else None,
                "min": min(data) if data else None,
                "max": max(data) if data else None,
                "median": sorted(data)[len(data) // 2] if data else None
            }
            
            # Calculate standard deviation
            mean = result["mean"]
            variance = sum((x - mean) ** 2 for x in data) / len(data) if data else 0
            result["std_dev"] = variance ** 0.5
        
        return result
    
    def _correlation_analysis(self, data: Any, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Calculate correlations between variables in the data."""
        result = {"correlations": {}}
        
        # If data is a list of dictionaries (tabular data)
        if isinstance(data, list) and all(isinstance(item, dict) for item in data):
            # Find numeric columns
            numeric_columns = []
            for column in data[0].keys():
                if all(column in item and isinstance(item[column], (int, float)) for item in data):
                    numeric_columns.append(column)
            
            # Calculate correlations between all pairs of numeric columns
            for i in range(len(numeric_columns)):
                for j in range(i+1, len(numeric_columns)):
                    col1 = numeric_columns[i]
                    col2 = numeric_columns[j]
                    
                    # Extract values
                    values1 = [item[col1] for item in data]
                    values2 = [item[col2] for item in data]
                    
                    # Calculate correlation coefficient
                    correlation = self._calculate_correlation(values1, values2)
                    
                    # Store result
                    if col1 not in result["correlations"]:
                        result["correlations"][col1] = {}
                    result["correlations"][col1][col2] = correlation
        
        return result
    
    def _calculate_correlation(self, x: List[float], y: List[float]) -> float:
        """Calculate Pearson correlation coefficient between two lists of values."""
        n = len(x)
        if n != len(y) or n == 0:
            return 0
        
        # Calculate means
        mean_x = sum(x) / n
        mean_y = sum(y) / n
        
        # Calculate covariance and variances
        covariance = sum((x[i] - mean_x) * (y[i] - mean_y) for i in range(n))
        variance_x = sum((val - mean_x) ** 2 for val in x)
        variance_y = sum((val - mean_y) ** 2 for val in y)
        
        # Calculate correlation coefficient
        if variance_x == 0 or variance_y == 0:
            return 0
        return covariance / ((variance_x * variance_y) ** 0.5)
    
    def _trend_analysis(self, data: Any, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze trends in time-series data."""
        result = {"trends": {}}
        
        # Extract time column and value column from parameters
        time_column = parameters.get("time_column", "time")
        value_column = parameters.get("value_column", "value")
        
        # If data is a list of dictionaries (tabular data)
        if isinstance(data, list) and all(isinstance(item, dict) for item in data):
            # Check if the specified columns exist
            if all(time_column in item and value_column in item for item in data):
                # Sort data by time
                sorted_data = sorted(data, key=lambda x: x[time_column])
                
                # Extract values
                times = [item[time_column] for item in sorted_data]
                values = [item[value_column] for item in sorted_data]
                
                # Calculate basic trend metrics
                if len(values) >= 2:
                    # Calculate slope (simple linear regression)
                    n = len(values)
                    if isinstance(times[0], (int, float)):
                        x = times
                    else:
                        # If time is not numeric, use indices
                        x = list(range(n))
                    
                    # Calculate slope (rise / run)
                    if max(x) != min(x):  # Avoid division by zero
                        slope = (values[-1] - values[0]) / (x[-1] - x[0])
                    else:
                        slope = 0
                    
                    # Determine trend direction
                    if slope > 0.05:  # Arbitrary threshold
                        direction = "increasing"
                    elif slope < -0.05:  # Arbitrary threshold
                        direction = "decreasing"
                    else:
                        direction = "stable"
                    
                    # Calculate percent change
                    if values[0] != 0:
                        percent_change = ((values[-1] - values[0]) / abs(values[0])) * 100
                    else:
                        percent_change = float('inf') if values[-1] > 0 else 0
                    
                    result["trends"][value_column] = {
                        "slope": slope,
                        "direction": direction,
                        "start_value": values[0],
                        "end_value": values[-1],
                        "percent_change": percent_change
                    }
                    
                    # Calculate moving average if enough data points
                    if len(values) >= 3:
                        window_size = min(3, len(values))
                        moving_avg = []
                        for i in range(len(values) - window_size + 1):
                            avg = sum(values[i:i+window_size]) / window_size
                            moving_avg.append(avg)
                        
                        result["trends"][f"{value_column}_moving_avg"] = moving_avg
        
        return result
    
    def _comparison_analysis(self, data: Any, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Compare different groups or categories in the data."""
        result = {"comparisons": {}}
        
        # Extract group column and value column from parameters
        group_column = parameters.get("group_column", "group")
        value_column = parameters.get("value_column", "value")
        
        # If data is a list of dictionaries (tabular data)
        if isinstance(data, list) and all(isinstance(item, dict) for item in data):
            # Check if the specified columns exist
            if all(group_column in item for item in data):
                # Group data by the group column
                groups = {}
                for item in data:
                    group = item[group_column]
                    if group not in groups:
                        groups[group] = []
                    
                    if value_column in item and isinstance(item[value_column], (int, float)):
                        groups[group].append(item[value_column])
                
                # Calculate statistics for each group
                for group, values in groups.items():
                    if values:
                        group_stats = {
                            "count": len(values),
                            "mean": sum(values) / len(values),
                            "min": min(values),
                            "max": max(values),
                            "median": sorted(values)[len(values) // 2]
                        }
                        
                        # Calculate standard deviation
                        mean = group_stats["mean"]
                        variance = sum((x - mean) ** 2 for x in values) / len(values)
                        group_stats["std_dev"] = variance ** 0.5
                        
                        result["comparisons"][group] = group_stats
                
                # Compare groups
                if len(groups) >= 2:
                    group_means = {group: stats["mean"] for group, stats in result["comparisons"].items()}
                    max_group = max(group_means, key=group_means.get)
                    min_group = min(group_means, key=group_means.get)
                    
                    result["group_comparison"] = {
                        "highest_mean": {
                            "group": max_group,
                            "value": group_means[max_group]
                        },
                        "lowest_mean": {
                            "group": min_group,
                            "value": group_means[min_group]
                        },
                        "difference": group_means[max_group] - group_means[min_group]
                    }
        
        return result
    
    def _frequency_analysis(self, data: Any, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze the frequency distribution of categorical data."""
        result = {"frequencies": {}}
        
        # Extract category column from parameters
        category_column = parameters.get("category_column", "category")
        
        # If data is a list of dictionaries (tabular data)
        if isinstance(data, list) and all(isinstance(item, dict) for item in data):
            # Check if the specified column exists
            if all(category_column in item for item in data):
                # Count frequencies
                frequencies = {}
                for item in data:
                    category = item[category_column]
                    if category not in frequencies:
                        frequencies[category] = 0
                    frequencies[category] += 1
                
                # Calculate percentages
                total_count = len(data)
                percentages = {category: (count / total_count) * 100 for category, count in frequencies.items()}
                
                # Sort by frequency (descending)
                sorted_categories = sorted(frequencies.keys(), key=lambda x: frequencies[x], reverse=True)
                
                # Combine results
                for category in sorted_categories:
                    result["frequencies"][category] = {
                        "count": frequencies[category],
                        "percentage": percentages[category]
                    }
                
                # Find most and least common
                if sorted_categories:
                    result["most_common"] = {
                        "category": sorted_categories[0],
                        "count": frequencies[sorted_categories[0]],
                        "percentage": percentages[sorted_categories[0]]
                    }
                    
                    result["least_common"] = {
                        "category": sorted_categories[-1],
                        "count": frequencies[sorted_categories[-1]],
                        "percentage": percentages[sorted_categories[-1]]
                    }
        
        return result
    
    def _basic_analysis(self, data: Any, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """Perform basic analysis on data."""
        result = {}
        
        # Determine data type and structure
        if isinstance(data, list):
            result["data_type"] = "list"
            result["count"] = len(data)
            
            # Check if list items are of uniform type
            if all(isinstance(item, dict) for item in data):
                result["item_type"] = "dict"
                
                # List columns if data is tabular
                if data:
                    result["columns"] = list(data[0].keys())
                    result["row_count"] = len(data)
                    result["column_count"] = len(result["columns"])
                    
                    # Infer column types
                    column_types = {}
                    for column in result["columns"]:
                        # Get non-None values for this column
                        values = [item[column] for item in data if column in item and item[column] is not None]
                        
                        if all(isinstance(v, int) for v in values):
                            column_types[column] = "integer"
                        elif all(isinstance(v, float) for v in values):
                            column_types[column] = "float"
                        elif all(isinstance(v, (int, float)) for v in values):
                            column_types[column] = "numeric"
                        elif all(isinstance(v, str) for v in values):
                            column_types[column] = "string"
                        else:
                            column_types[column] = "mixed"
                    
                    result["column_types"] = column_types
            
            elif all(isinstance(item, (int, float)) for item in data):
                result["item_type"] = "numeric"
                result["mean"] = sum(data) / len(data) if data else None
                result["min"] = min(data) if data else None
                result["max"] = max(data) if data else None
            
            elif all(isinstance(item, str) for item in data):
                result["item_type"] = "string"
                result["unique_count"] = len(set(data))
            
            else:
                result["item_type"] = "mixed"
        
        elif isinstance(data, dict):
            result["data_type"] = "dict"
            result["key_count"] = len(data)
            result["keys"] = list(data.keys())
        
        return result
