# tools/information_extraction_tool.py
# Generated by Claude

"""
Tool for identifying and extracting specific pieces of information from text.
"""
from typing import Dict, List, Any, Optional
import re
import json

class InformationExtractionTool:
    """Tool for extracting specific information from text based on instructions."""
    
    def __init__(self):
        """Initialize the InformationExtractionTool."""
        # Track extracted information for citation purposes
        self.extraction_history = []
        
    def extract(self, text: str, instructions: str, source: Optional[str] = None) -> Dict[str, Any]:
        """
        Extract specific information from text based on instructions.
        
        Args:
            text: The text to extract information from
            instructions: Instructions specifying what information to extract
            source: Optional source reference for citation purposes
            
        Returns:
            A dictionary containing the extracted information and metadata
        """
        # In a real implementation, this would use more sophisticated NLP techniques
        # For demonstration, we'll use a combination of rules and simpler approaches
        
        instructions_lower = instructions.lower()
        
        # Determine the type of extraction needed
        if "statistic" in instructions_lower or "number" in instructions_lower:
            extracted_info = self._extract_statistics(text, instructions)
            extraction_type = "statistics"
        elif "main point" in instructions_lower or "key finding" in instructions_lower:
            extracted_info = self._extract_key_findings(text, instructions)
            extraction_type = "key_findings"
        elif "quote" in instructions_lower or "statement" in instructions_lower:
            extracted_info = self._extract_quotes(text, instructions)
            extraction_type = "quotes"
        elif "definition" in instructions_lower or "meaning" in instructions_lower:
            extracted_info = self._extract_definitions(text, instructions)
            extraction_type = "definitions"
        else:
            # General extraction
            extracted_info = self._general_extraction(text, instructions)
            extraction_type = "general"
        
        # Create result object
        result = {
            "success": True if extracted_info else False,
            "instructions": instructions,
            "extraction_type": extraction_type,
            "extracted_information": extracted_info,
            "source": source
        }
        
        # Track extraction for citation purposes
        self.extraction_history.append({
            "text_snippet": text[:100] + "..." if len(text) > 100 else text,
            "instructions": instructions,
            "extraction_type": extraction_type,
            "source": source,
            "time": import time; time.time(),
            "result": extracted_info
        })
        
        return result
    
    def _extract_statistics(self, text: str, instructions: str) -> List[Dict[str, Any]]:
        """Extract statistics or numerical data from text."""
        # Look for patterns like "X%" or "X million" or numerical values
        # For demonstration, using simple regex patterns
        
        statistics = []
        
        # Extract percentages
        percentage_pattern = r"(\d+(?:\.\d+)?)\s*%"
        percentages = re.findall(percentage_pattern, text)
        for p in percentages:
            # Get surrounding context
            match_obj = re.search(f"{p}\s*%", text)
            if match_obj:
                start = max(0, match_obj.start() - 50)
                end = min(len(text), match_obj.end() + 50)
                context = text[start:end]
                statistics.append({
                    "type": "percentage",
                    "value": f"{p}%",
                    "context": context
                })
        
        # Extract numbers with units
        number_unit_pattern = r"(\d+(?:,\d+)*(?:\.\d+)?)\s*(million|billion|trillion|thousand)"
        number_units = re.findall(number_unit_pattern, text)
        for nu in number_units:
            # Get surrounding context
            match_obj = re.search(f"{nu[0]}\s*{nu[1]}", text)
            if match_obj:
                start = max(0, match_obj.start() - 50)
                end = min(len(text), match_obj.end() + 50)
                context = text[start:end]
                statistics.append({
                    "type": "quantity",
                    "value": f"{nu[0]} {nu[1]}",
                    "context": context
                })
        
        # Filter based on instructions if needed
        if "about" in instructions.lower():
            topic = instructions.lower().split("about")[-1].strip()
            filtered_stats = []
            for stat in statistics:
                if topic in stat["context"].lower():
                    filtered_stats.append(stat)
            return filtered_stats
        
        return statistics
    
    def _extract_key_findings(self, text: str, instructions: str) -> List[Dict[str, str]]:
        """Extract key findings or main points from text."""
        # In a real implementation, this would use more sophisticated techniques
        # For demonstration, we'll look for key phrases and sentence structure
        
        findings = []
        
        # Split text into sentences
        sentences = re.split(r'(?<=[.!?])\s+', text)
        
        # Look for sentences that might contain key findings
        key_phrases = [
            "key finding", "main point", "important", "significant", 
            "conclude", "conclusion", "result", "discover", "discovery",
            "demonstrate", "show", "reveal", "highlight", "indicate"
        ]
        
        for sentence in sentences:
            # Check if the sentence contains any key phrases
            if any(phrase in sentence.lower() for phrase in key_phrases):
                findings.append({
                    "finding": sentence.strip(),
                    "type": "key_phrase_match"
                })
                
        # If no key phrases found, try to extract based on sentence position
        if not findings and len(sentences) > 3:
            # First sentence might be a key finding
            findings.append({
                "finding": sentences[0].strip(),
                "type": "position_based_first"
            })
            
            # Last sentence in a paragraph might be a conclusion
            findings.append({
                "finding": sentences[-1].strip(),
                "type": "position_based_last"
            })
        
        return findings
    
    def _extract_quotes(self, text: str, instructions: str) -> List[Dict[str, str]]:
        """Extract quotes or direct statements from text."""
        quotes = []
        
        # Look for text within quotation marks
        quote_pattern = r'"([^"]*)"'
        extracted_quotes = re.findall(quote_pattern, text)
        
        for quote in extracted_quotes:
            quotes.append({
                "quote": quote,
                "type": "direct_quote"
            })
        
        # Alternative quotation style
        alt_quote_pattern = r''([^']*)''
        alt_quotes = re.findall(alt_quote_pattern, text)
        
        for quote in alt_quotes:
            quotes.append({
                "quote": quote,
                "type": "direct_quote"
            })
        
        # Look for indirect quotes (stated by, according to, etc.)
        indirect_patterns = [
            r"according to ([^,.;:]+), ([^.;:]+)",
            r"([^,.;:]+) stated that ([^.;:]+)",
            r"([^,.;:]+) said that ([^.;:]+)",
            r"([^,.;:]+) reported that ([^.;:]+)"
        ]
        
        for pattern in indirect_patterns:
            matches = re.findall(pattern, text)
            for match in matches:
                quotes.append({
                    "source": match[0],
                    "quote": match[1],
                    "type": "indirect_quote"
                })
        
        return quotes
    
    def _extract_definitions(self, text: str, instructions: str) -> List[Dict[str, str]]:
        """Extract definitions or explanations of terms from text."""
        definitions = []
        
        # Try to identify what term needs to be defined
        term = None
        if "of" in instructions.lower():
            parts = instructions.lower().split("of")
            if len(parts) > 1:
                term = parts[1].strip()
        
        if term:
            # Look for patterns like "term is defined as" or "term refers to"
            definition_patterns = [
                f"{term} is defined as ([^.;:]+)",
                f"{term} refers to ([^.;:]+)",
                f"{term} means ([^.;:]+)",
                f"{term}: ([^.;:]+)",
                f"{term} - ([^.;:]+)"
            ]
            
            for pattern in definition_patterns:
                matches = re.findall(pattern, text, re.IGNORECASE)
                for match in matches:
                    definitions.append({
                        "term": term,
                        "definition": match.strip(),
                        "type": "explicit_definition"
                    })
            
            # If no explicit definition found, try to extract sentences containing the term
            if not definitions:
                sentences = re.split(r'(?<=[.!?])\s+', text)
                for sentence in sentences:
                    if term in sentence.lower():
                        definitions.append({
                            "term": term,
                            "context": sentence.strip(),
                            "type": "context_definition"
                        })
        else:
            # Look for general definitional patterns
            patterns = [
                r"([^\s]+) is defined as ([^.;:]+)",
                r"([^\s]+) refers to ([^.;:]+)",
                r"([^\s]+) means ([^.;:]+)",
                r"definition of ([^\s]+): ([^.;:]+)"
            ]
            
            for pattern in patterns:
                matches = re.findall(pattern, text, re.IGNORECASE)
                for match in matches:
                    definitions.append({
                        "term": match[0],
                        "definition": match[1].strip(),
                        "type": "general_definition"
                    })
        
        return definitions
    
    def _general_extraction(self, text: str, instructions: str) -> List[Dict[str, Any]]:
        """General purpose information extraction based on instructions."""
        extracted_info = []
        
        # Simple keyword-based extraction
        # Extract sentences containing key terms from the instructions
        key_terms = [word for word in instructions.lower().split() if len(word) > 3]
        
        # Remove common words
        common_words = ["what", "where", "when", "find", "identify", "extract", "about", "information", "this", "that", "these", "those"]
        key_terms = [term for term in key_terms if term not in common_words]
        
        if key_terms:
            sentences = re.split(r'(?<=[.!?])\s+', text)
            for sentence in sentences:
                sentence_lower = sentence.lower()
                for term in key_terms:
                    if term in sentence_lower:
                        extracted_info.append({
                            "content": sentence.strip(),
                            "matched_term": term,
                            "type": "keyword_match"
                        })
                        break  # Only add the sentence once
        
        return extracted_info
