# tools/report_generation_tool.py
# Generated by Claude.
"""
Tool for formatting and structuring the final research report.
"""
from typing import Dict, List, Any, Optional

class ReportGenerationTool:
    """Tool for generating structured research reports with citations."""
    
    def __init__(self):
        """Initialize the ReportGenerationTool."""
        pass
    
    def generate_report(self, 
                        title: str, 
                        sections: List[Dict[str, Any]], 
                        citations: List[Dict[str, Any]], 
                        format: str = "markdown") -> Dict[str, Any]:
        """
        Generate a structured research report with proper citations.
        
        Args:
            title: The title of the report
            sections: List of section dictionaries with content and claims
            citations: List of citation dictionaries
            format: Output format (markdown, html, txt)
            
        Returns:
            A dictionary containing the generated report
        """
        if format.lower() == "markdown":
            report_content = self._generate_markdown_report(title, sections, citations)
        elif format.lower() == "html":
            report_content = self._generate_html_report(title, sections, citations)
        else:  # default to plain text
            report_content = self._generate_text_report(title, sections, citations)
        
        return {
            "title": title,
            "format": format,
            "content": report_content,
            "sections_count": len(sections),
            "citations_count": len(citations)
        }
    
    def _generate_markdown_report(self, 
                                  title: str, 
                                  sections: List[Dict[str, Any]], 
                                  citations: List[Dict[str, Any]]) -> str:
        """Generate a research report in Markdown format."""
        report = f"# {title}\n\n"
        
        # Add abstract if present
        abstract_section = next((s for s in sections if s.get("type") == "abstract"), None)
        if abstract_section:
            report += f"## Abstract\n\n{abstract_section['content']}\n\n"
        
        # Add introduction if present
        intro_section = next((s for s in sections if s.get("type") == "introduction"), None)
        if intro_section:
            report += f"## Introduction\n\n{intro_section['content']}\n\n"
        
        # Add main content sections
        main_sections = [s for s in sections if s.get("type") not in ["abstract", "introduction", "conclusion", "references"]]
        for section in main_sections:
            report += f"## {section['title']}\n\n"
            
            # Add content with citations
            content = section['content']
            
            # If there are claims associated with this section, add citations
            if 'claims' in section:
                for claim in section['claims']:
                    if 'citation_id' in claim and claim['citation_id'] < len(citations):
                        citation = citations[claim['citation_id']]
                        # Replace the claim text with the claim + citation
                        content = content.replace(
                            claim['text'], 
                            f"{claim['text']} {citation['in_text_citation']}"
                        )
            
            report += f"{content}\n\n"
            
            # Add subsections if present
            if 'subsections' in section:
                for subsection in section['subsections']:
                    report += f"### {subsection['title']}\n\n{subsection['content']}\n\n"
        
        # Add conclusion if present
        conclusion_section = next((s for s in sections if s.get("type") == "conclusion"), None)
        if conclusion_section:
            report += f"## Conclusion\n\n{conclusion_section['content']}\n\n"
        
        # Add references
        report += "## References\n\n"
        
        # Collect all unique references
        unique_references = {}
        for citation in citations:
            if 'reference' in citation:
                unique_references[citation['reference']] = True
        
        # Add references in alphabetical order
        for reference in sorted(unique_references.keys()):
            report += f"{reference}\n\n"
        
        return report
    
    def _generate_html_report(self, 
                             title: str, 
                             sections: List[Dict[str, Any]], 
                             citations: List[Dict[str, Any]]) -> str:
        """Generate a research report in HTML format."""
        report = f"""<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; margin: 2em; }}
        h1 {{ color: #333; }}
        h2 {{ color: #444; margin-top: 1.5em; }}
        h3 {{ color: #555; }}
        .abstract {{ font-style: italic; margin-bottom: 2em; }}
        .citation {{ vertical-align: super; font-size: 0.8em; }}
        .references {{ margin-top: 2em; border-top: 1px solid #ccc; padding-top: 1em; }}
        .reference {{ margin-bottom: 0.5em; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
"""
        
        # Add abstract if present
        abstract_section = next((s for s in sections if s.get("type") == "abstract"), None)
        if abstract_section:
            report += f"    <div class='abstract'>\n        <h2>Abstract</h2>\n        <p>{abstract_section['content']}</p>\n    </div>\n"
        
        # Add introduction if present
        intro_section = next((s for s in sections if s.get("type") == "introduction"), None)
        if intro_section:
            report += f"    <h2>Introduction</h2>\n    <p>{intro_section['content']}</p>\n"
        
        # Add main content sections
        main_sections = [s for s in sections if s.get("type") not in ["abstract", "introduction", "conclusion", "references"]]
        for section in main_sections:
            report += f"    <h2>{section['title']}</h2>\n"
            
            # Add content with citations
            content = section['content']
            
            # If there are claims associated with this section, add citations
            if 'claims' in section:
                for i, claim in enumerate(section['claims']):
                    if 'citation_id' in claim and claim['citation_id'] < len(citations):
                        citation = citations[claim['citation_id']]
                        # Replace the claim text with the claim + citation
                        content = content.replace(
                            claim['text'], 
                            f"{claim['text']} <sup>[{i+1}]</sup>"
                        )
            
            report += f"    <p>{content}</p>\n"
            
            # Add subsections if present
            if 'subsections' in section:
                for subsection in section['subsections']:
                    report += f"    <h3>{subsection['title']}</h3>\n    <p>{subsection['content']}</p>\n"
        
        # Add conclusion if present
        conclusion_section = next((s for s in sections if s.get("type") == "conclusion"), None)
        if conclusion_section:
            report += f"    <h2>Conclusion</h2>\n    <p>{conclusion_section['content']}</p>\n"
        
        # Add references
        report += "    <div class='references'>\n        <h2>References</h2>\n"
        
        # Collect all unique references
        unique_references = {}
        for i, citation in enumerate(citations):
            if 'reference' in citation:
                unique_references[i] = citation['reference']
        
        # Add references with numbering
        for i, reference in sorted(unique_references.items()):
            report += f"        <p class='reference'>[{i+1}] {reference}</p>\n"
        
        report += "    </div>\n</body>\n</html>"
        
        return report
    
    def _generate_text_report(self, 
                             title: str, 
                             sections: List[Dict[str, Any]], 
                             citations: List[Dict[str, Any]]) -> str:
        """Generate a research report in plain text format."""
        report = f"{title.upper()}\n{'=' * len(title)}\n\n"
        
        # Add abstract if present
        abstract_section = next((s for s in sections if s.get("type") == "abstract"), None)
        if abstract_section:
            report += f"ABSTRACT\n--------\n\n{abstract_section['content']}\n\n"
        
        # Add introduction if present
        intro_section = next((s for s in sections if s.get("type") == "introduction"), None)
        if intro_section:
            report += f"INTRODUCTION\n------------\n\n{intro_section['content']}\n\n"
        
        # Add main content sections
        main_sections = [s for s in sections if s.get("type") not in ["abstract", "introduction", "conclusion", "references"]]
        for section in main_sections:
            report += f"{section['title'].upper()}\n{'-' * len(section['title'])}\n\n"
            
            # Add content with citations
            content = section['content']
            
            # If there are claims associated with this section, add citations
            if 'claims' in section:
                for claim in section['claims']:
                    if 'citation_id' in claim and claim['citation_id'] < len(citations):
                        citation = citations[claim['citation_id']]
                        # Replace the claim text with the claim + citation
                        content = content.replace(
                            claim['text'], 
                            f"{claim['text']} {citation['in_text_citation']}"
                        )
            
            report += f"{content}\n\n"
            
            # Add subsections if present
            if 'subsections' in section:
                for subsection in section['subsections']:
                    report += f"{subsection['title']}\n{'^' * len(subsection['title'])}\n\n{subsection['content']}\n\n"
        
        # Add conclusion if present
        conclusion_section = next((s for s in sections if s.get("type") == "conclusion"), None)
        if conclusion_section:
            report += f"CONCLUSION\n----------\n\n{conclusion_section['content']}\n\n"
        
        # Add references
        report += "REFERENCES\n----------\n\n"
        
        # Collect all unique references
        unique_references = {}
        for citation in citations:
            if 'reference' in citation:
                unique_references[citation['reference']] = True
        
        # Add references in alphabetical order
        for reference in sorted(unique_references.keys()):
            report += f"{reference}\n\n"
        
        return report
